### ISSUE TITLE
request more detailed comments about folder experiment.

### ISSUE THREAD

**Issue by nooooonee** [columbia/pixeldp#6]
Some code bugs:
1. Can the variable "d" be removed safely in line 89 of experiments/cifar10_robust_prec.py?
2. 'L_sigmas' is not defined in cifar10_eval.py
3.  The variable 'max_attack_size' is not defined in line 190 of experiments/cifar10_robust_prec.py, maybe it should be 'attack_size'?

Addition:
Could you give more detailed annotations about each file in experiments folder?  It's not so easy to see which file is used to plot a certain figure in the paper?

Thanks in advance.

**Comment by m-lecuyer** [comment]
Your are welcome to send pull requests if there are improvements you'd like to make. But as a fair warning this code is not meant to be maintained as a solid and well documented library. It shows the code we used for the paper to share the details and allow anyone to take pieces for future research. Our own research follow-ups may not build on this code directly.
