### ISSUE TITLE
Problems about PGD attack

### ISSUE THREAD

**Issue by YuhengHuang42** [columbia/pixeldp#8]
Dear author,

Thanks for your brilliant work. After reading your paper, I am interested in the performance of pixeldp_cnn under PGD attack. I notice that you have implemented one in this repo (Just as the paper mentioned in the Appendix). However, It seems that something is missing. 

First of all, in the train_attack.py, the initialization of the attack:
`attack = attack_class.Attack`
is only for the Carlini. However Carlini has different parameters with PGD for initialization.

What's more, in the pgd.py, parameters like 
`self.min_pix = min_pix`
`self.max_pix = max_pix`
are also missing.

**Comment by m-lecuyer** [comment]
Ah yes we probably messed things up when refactoring before putting the code online, sorry. It should work if you pass the correct constructor in train_attack.train_one().
I don't have all the code details in mind anymore unfortunately, but it looks like min/max_pix were replaced with boxmin/max to be consistent with the Carlini attack, so you'll have to replace that too.
